insert into job_applied
    (job_id ,
    application_sent_date ,
    Custome_resume ,
    resume_file_name ,
    cover_letter_sent ,
    cover_letter_file_name ,
    status )
values (1,
    '2024-03-19',
    true,
    'resume_01.pdf',
    true,
    'cover_letter_01.pdf',
    'submitted'),
    (2,
    '2024-03-20',
    true,
    'resume_02.pdf',
    true,
    'cover_letter_02.pdf',
    'ghosted'),
        (3,
    '2024-03-21',
    false,
    'resume_03.pdf',
    true,
    'cover_letter_03.pdf',
    'submitted'),
        (4,
    '2024-03-22',
    false,
    'resume_04.pdf',
    true,
    'cover_letter_04.pdf',
    'rejected'),
        (5,
    '2024-03-23',
    false,
    'resume_05.pdf',
    false,
    'cover_letter_05.pdf',
    'no_response'
);